### ISSUE TITLE
Upgrade to Azure Functions 3.0 and GraphQL 3.0.0

### ISSUE THREAD

**Issue by tpeczek** [tpeczek/Demo.Azure.Functions.GraphQL#1]

**Comment by jg-fisher** [comment]
Hey, any updates on this?

**Comment by tpeczek** [comment]
Upgrade to Azure Functions 3.0 has been done some time ago.

I see that GraphQL 3.0.0 has been released last month, so I guess I can jump on this one once I'll have some time.
